# Generated by Django 5.1.1 on 2025-10-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_bought_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_address',
        ),
    ]
