# Generated by Django 5.1.1 on 2025-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_buyer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_signature',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
