# Generated by Django 5.1.1 on 2025-10-23 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_icon_class_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(choices=[('bi-tag-fill', 'Default / Miscellaneous'), ('bi-sun-fill', 'Patio / Garden')], default='bi-tag-fill', help_text='Select a Bootstrap icon class to display next to the category name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('rating__lte', 10)), name='core_product_rating_max_10'),
        ),
    ]
