# Generated by Django 5.1.1 on 2025-10-23 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_icon_class_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='core_product_rating_max_10',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(choices=[('bi-tag-fill', 'Default / Miscellaneous'), ('bi-phone-fill', 'Mobile Phones'), ('bi-laptop-fill', 'Laptops & Computers'), ('bi-tablet-fill', 'Tables & E-Readers'), ('bi-watch', 'Smart Watches'), ('bi-headphones', 'Audio / Headphones'), ('bi-speaker-fill', 'Speakers & Sound'), ('bi-mouse-fill', 'Mice / Peripherals'), ('bi-keyboard-fill', 'Keyboards'), ('bi-controller', 'Gaming'), ('bi-camera-fill', 'Cameras / Photography'), ('bi-cpu-fill', 'Computer Components'), ('bi-tv-fill', 'Televisions'), ('bi-house-fill', 'Home & Decor'), ('bi-lightning-fill', 'Appliances / Electric'), ('bi-droplet-fill', 'Kitchenware'), ('bi-wrench-adjustable-fill', 'Tools & DIY'), ('bi-lamp-fill', 'Lighting'), ('bi-door-closed-fill', 'Furniture'), ('bi-plug-fill', 'Cables & Power'), ('bi-bag-fill', 'Bags & Luggage'), ('bi-tshirt-fill', 'Clothing / Apparel'), ('bi-gem', 'Jewelry & Accessories'), ('bi-eyeglasses', 'Eyewear'), ('bi-shoe-fill', 'Footwear'), ('bi-book-fill', 'Books & Literature'), ('bi-journal-richtext', 'Office Supplies'), ('bi-vinyl-fill', 'Music & Media'), ('bi-pencil-fill', 'Art Supplies'), ('bi-bicycle', 'Sports & Cycling'), ('bi-heart-pulse-fill', 'Fitness / Health'), ('bi-globe', 'Outdoors / Travel'), ('bi-sun-fill', 'Patio / Garden')], default='bi-tag-fill', help_text='Select a Bootstrap icon class to display next to the category name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Rating must be between 0 and 10.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
