# Generated by Django 5.1.1 on 2025-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_core_product_rating_max_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('used', 'Used')], default='new', help_text='Is this product new or used?', max_length=4),
        ),
    ]
