# Generated by Django 5.1.1 on 2025-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Chapa transaction reference', max_length=100, null=True, unique=True),
        ),
    ]
